### ISSUE TITLE
Org Schema: data_locations shape

### ISSUE THREAD

**Issue by blaiszik** [materials-data-facility/connect_server#31]
For org schema, should data_locations require an object of shape {"endpoint":"UUID", "path":""}?

**Comment by jgaff** [comment]
The `data_locations` mirrors our `data.endpoint_path` in the dataset schema, which follows the format `globus://[ep-id]/[path]`. Leaving the `data_locations` as a list of strings also allows us to expand the allowed destination formats in the future if we decide we want to (and can).
