### ISSUE TITLE
Request: remove mass_update_search or convert to use Ingest API

### ISSUE THREAD

**Issue by sirosen** [materials-data-facility/connect_server#37]
Search is unifying this on the backend right now, so that calls to POST or PUT an entry will actually submit an Ingest task. This is being done to unify a lot of the logic around handling these updates and avoid many of the pitfalls that we had with synchronous Ingest operations in the past.

However, making these the same internally leaves me questioning the value of having a separate API for these at all. I think it would be better -- both for Search and for its users, like MDF -- if we eliminated the POST/PUT entry APIs ( update_entry and create_entry in the SDK) and removed the relevant SDK methods.
I don't want to cause unnecessary breakage, so I'd like to see the code here using `update_entry` switch to using ingest:

https://github.com/materials-data-facility/connect_server/blob/f44b8b75e1dc1cb6c9a5c1f179b7d126550fd7ad/mdf_connect_server/utils/search_ingester.py#L324

Either that or remove it if it's unused. The multiprocessing ingest flow is probably better and faster in all ways, based on my reading of this module.

**Comment by jgaff** [comment]
Cool. I can put this in my queue. Modifying `mass_update_search` to just use our existing ingest tooling makes things simpler, which I'm always a fan of. However, I'd like to ask some questions about the behavior of updates as ingests.

Assuming I have an entry in Search that looks like this:
```
{
    "foo": 123,
    "bar": [1, 2, 3],
    "baz": "abc"
}
```
and I submit an ingest with the same `subject` that looks like this:
```
{
    "foo": 456,
    "bar": [4, 5, 6],
    "qux": "def"
}
```
what will the resulting entry in Search look like? I'm primarily wondering if `.ingest()` will overwrite or merge when presented with an update of an existing entry, and (if it merges) how the merge is performed.

**Comment by sirosen** [comment]
Ingest always overwrites, as does `update_entry` today. The only kind of merge semantics you should ever see is that writing two entries with distinct entry IDs should result in both being present in the resulting document, as you would expect.

This case is, in fact, one of the things that is improved by switching everything to be an Ingest Task. Today, trying to write both of those documents at once can cause one or even both of those operations to fail if the timing is _just wrong_. By using async Ingest, we serialize and control these two writes, so that the "later one" wins. Search is responsible for deciding which one is "later", of course.

**Comment by jgaff** [comment]
Right, I was wondering if there was any actual update functionality coming to `.ingest()` with this change (so `mass_update_search` wouldn't need to pull the existing entries before the update call), but I can work with `.ingest()` just being the way to tell Search "set this subject+entry_id to this value."

**Comment by sirosen** [comment]
A partial document update like this isn't something I've considered before. I'll give it some thought and at least file it as a feature request. While it can, at least in theory, be done more efficiently by Search, it's not a trivial feature and I have a few concerns about adding it.
