### ISSUE TITLE
Evaluate new Groups API

### ISSUE THREAD

**Issue by blaiszik** [materials-data-facility/connect_server#53]
Swapping to the new Groups API may be helpful for our needs.

It does not yet seem to have a Python client. https://docs.globus.org/api/groups/

**Comment by jgaff** [comment]
As discussed, the new Groups API appears to be able to serve our purposes, but migration will wait until official Globus SDK support is developed. There is no urgency, as we've already put in the work to get our use cases working with the Nexus API and the new API does not seem to offer any significant advantages (until Nexus is deprecated, that is).

**Comment by BenGalewsky** [comment]
Will be closed via #104
