### ISSUE TITLE
Clear "test" submissions

### ISSUE THREAD

**Issue by blaiszik** [materials-data-facility/connect_server#55]
We should put into place scripts that run regularly to clear out old test submissions from the database.

Perhaps the script could run from the server each day and clear out any "test" submissions older than 14 days

**Comment by blaiszik** [comment]
For clarity, this would only remove the submissions from the AWS Dyanamo table rather than clear the search index or delete the contents of the endpoint.

**Comment by jgaff** [comment]
I don't understand the case here; what purpose does clearing test submissions from the status database serve?

**Comment by blaiszik** [comment]
We don't have paging or filtering (other than on active vs not active) in MDF Connect Client `check_all_submissions` function. So, after you have submitted lots of test datasets it gets quite heavy quickly to see your own history in the UI or in the Python client.

**Comment by jgaff** [comment]
Are you going to want more fine-grained filters for `check_all_submissions` later on? That would also solve the issue of seeing too many submissions. If not, I'll have the server purge old test submissions on startup (a daily cronjob-type check might eat too many Dynamo reads as it scans the whole status DB).

**Comment by blaiszik** [comment]
Filtering by submission type (test, vs not test) would be a good start. Filter by date might also be helpful, but might not be necessary in the near term.

Removing test submissions on startup seems like a good idea. That will also help to limit our DB reads over time.

**Comment by jgaff** [comment]
Okay, so you'd prefer both solutions. I've added those tasks to my Asana, and I'll start work on them today.

**Comment by jgaff** [comment]
As I'm starting this work, I've realized that deleting a submission from the status database without also deleting the corresponding entries from Search is not a good idea. The status database is consulted when determining a submission's version. If a previous submission is missing from the status database, the wrong submission version could be applied to the new submission, which could cause collisions or duplicates in Search.

Do you want me to 1) Keep test submissions in the status database (do not delete old ones), or 2) Delete the Search entries for old test submissions (optionally also deleting the files), effectively erasing test submissions entirely after 14 days?

**Comment by blaiszik** [comment]
I think it's ok to go with solution 2 given:

1) We test the delete query to ensure we don't delete more than we expect
2) Let's bump the time from 14 days to 30 days to given people time to test if needed.

**Comment by jgaff** [comment]
Sure thing.
1) Deleting a submission from Search is a solved problem - I already have well-tested code to do so. I will obviously be testing this functionality as well.
2) I'm making the time limit configurable, so we can adjust it as desired. Especially for test submissions, 30 days is a good, generous time limit. (In reality, test submissions older than 30 days will be present until the service restarts; 30 days is the guaranteed minimum time-to-live.)
