### ISSUE TITLE
Deploy MDF Serverless Lambda With Containers

### ISSUE THREAD

**Issue by BenGalewsky** [materials-data-facility/connect_server#84]
# Problem
Right now we deploy the python code and dependencies to AWS Lambda using a [GitHub action](https://github.com/materials-data-facility/connect_server/blob/serverless/.github/workflows/deploy-lambda.yml). It always deploys to a specific lambda. It also builds a new set of dependencies and deploys that the Lambda, but doesn't update the dependency link in the functions.

# Assumptions
1. Add Dockerfile to repo
2. Make a GHA to build the docker image and push to ECR
3. Use aws lambda update to force the lambda to pick up the new image

**Comment by ericblau** [comment]
Terraform scripts to create the lambdas for container deployment have been written.  They need to get deployed and evaluated

**Comment by ericblau** [comment]
Have not been able to solve issues with bootstrapping the lamdba containers in ECR, since coming back from vacation.  Still working on it.

**Comment by ericblau** [comment]
Bootstrapping issue has been resolved.  However, there remains an issue where the trigger for the lambda function is not being applied, resulting in the lambda never being called when hitting the api endpoint.  (Auth does happen correctly).  Per discussion w/ BenG, we're pausing on this until we have all the roles set up such that I'm not the only one who can apply this terraform

**Comment by BenGalewsky** [comment]
Blocked on #76

**Comment by ascourtas** [comment]
jiggle the AWS Lambda to pick up the new image -- unblocked!
